---
- name: Check if Google Chrome is already installed
  ansible.builtin.command: google-chrome --version
  register: chrome_check
  failed_when: false
  changed_when: false

- name: Setup Google Chrome repository for Ubuntu
  block:
    - name: Download Google public GPG key
      ansible.builtin.get_url:
        url: https://dl.google.com/linux/linux_signing_key.pub
        dest: /usr/share/keyrings/google-chrome.asc
      become: true

    - name: Add Google Chrome repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.asc] http://dl.google.com/linux/chrome/deb/ stable main"
        filename: google-chrome
        state: present
      become: true
  when: 
    - ansible_distribution == 'Ubuntu'
    - chrome_check.rc != 0
