---
- name: Install packages via winget
  community.windows.win_winget:
    name: "{{ item }}"
    state: present
  loop: "{{ win_pkgs.winget | default([]) }}"
  when: (win_pkgs.winget | default([])) | length > 0
  ignore_errors: true
