---
- hosts: localhost
  connection: local
  gather_facts: true
  vars:
    normal_user: "{{ lookup('env', 'SUDO_USER') | default(lookup('env', 'USER'), true) }}"
  tasks:
    - name: Test become to same user
      ansible.builtin.command: whoami
      become: true
      become_user: "{{ normal_user }}"
