---
- name: Install app on macOS via Homebrew Cask
  community.general.homebrew_cask:
    name: "{{ pkg_name }}"
    state: present
  register: brew_cask_install

- name: Add app to macOS Dock
  ansible.builtin.include_tasks: "{{ playbook_dir }}/_shared_tasks/mac_add_to_dock.yml"
  vars:
    dock_app_name: "{{ app_name }}"
  when:
    - app_name is defined
    - app_name | length > 0
    - selections.apps[role_name] is defined
    - selections.apps[role_name].add_to_dock | default(false)
    - brew_cask_install.changed
