---
- name: Check current cask state
  ansible.builtin.command: brew list --cask {{ pkg_name }}
  register: app_mac_state
  changed_when: false
  failed_when: false

- name: Install app on macOS
  ansible.builtin.command: brew install --cask {{ pkg_name }}
  when: app_mac_state.rc != 0

- name: Add app to macOS Dock
  ansible.builtin.include_tasks: "{{ playbook_dir }}/_shared_tasks/mac_add_to_dock.yml"
  vars:
    dock_app_name: "{{ app_name }}"
  when:
    - app_name is defined
    - app_name | length > 0
    - selections.apps[ansible_role_name] is defined
    - selections.apps[ansible_role_name].add_to_dock | default(false)
