---
- name: Check if dockutil is installed
  ansible.builtin.command: which dockutil
  register: dockutil_check
  changed_when: false
  failed_when: false

- name: Ensure dockutil is installed
  ansible.builtin.command: brew install dockutil
  when: dockutil_check.rc != 0

- name: Add app to macOS Dock
  ansible.builtin.command: dockutil --add '/Applications/{{ dock_app_name }}.app' --no-restart
  register: dockutil_result
  failed_when: false
  changed_when: dockutil_result.rc == 0

- name: Set pinned fact
  ansible.builtin.set_fact:
    role_pinned: true
  when: dockutil_result.changed or dockutil_result.rc == 0
