---
- name: "Process role: {{ role_name }} in category: {{ role_category }}"
  block:
    - name: "Check for user pre-tasks for {{ role_name }}"
      ansible.builtin.include_tasks: "{{ playbook_dir }}/config/{{ role_category }}/{{ role_name }}/pre.yml"
      when: (playbook_dir + '/config/' + role_category + '/' + role_name + '/pre.yml') is exists

    - name: "Include role: {{ role_name }}"
      ansible.builtin.include_role:
        name: "{{ role_name }}"

    - name: "Check for user post-tasks for {{ role_name }}"
      ansible.builtin.include_tasks: "{{ playbook_dir }}/config/{{ role_category }}/{{ role_name }}/post.yml"
      when: (playbook_dir + '/config/' + role_category + '/' + role_name + '/post.yml') is exists
  when:
    - selections[role_category][role_name] is defined
    - selections[role_category][role_name].enabled | default(false)
