---
- name: Skip when mac package id is undefined
  ansible.builtin.debug:
    msg: macOS package id is not defined for this role.
  when: app_pkg_mac | length == 0

- name: Check current cask state
  ansible.builtin.command: brew list --cask {{ app_pkg_mac }}
  register: app_mac_state
  changed_when: false
  failed_when: false
  when: app_pkg_mac | length > 0

- name: Install app on macOS
  ansible.builtin.command: brew install --cask {{ app_pkg_mac }}
  when:
    - app_pkg_mac | length > 0
    - app_mac_state.rc != 0
