---
- name: Check if Google Cloud SDK is already installed
  ansible.builtin.command: gcloud --version
  register: gcloud_check
  failed_when: false
  changed_when: false

- name: Setup Google Cloud SDK repository for Ubuntu
  block:
    - name: Install prerequisite packages
      ansible.builtin.package:
        name:
          - apt-transport-https
          - ca-certificates
          - gnupg
          - curl
        state: present
      become: true

    - name: Download Google Cloud public GPG key
      ansible.builtin.get_url:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        dest: /usr/share/keyrings/cloud.google.gpg
      become: true

    - name: Add Google Cloud SDK repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main"
        filename: google-cloud-sdk
        state: present
      become: true
  when: 
    - ansible_distribution == 'Ubuntu'
    - gcloud_check.rc != 0
