---
- name: Install gemini via npm
  community.general.npm:
    name: "@google/gemini-cli"
    global: yes
  become: "{{ true if ansible_system == 'Linux' else false }}"
  when: ansible_system != 'Win32NT'

- name: Install gemini via npm on Windows
  community.general.npm:
    name: "@google/gemini-cli"
    global: yes
  when: ansible_system == 'Win32NT'
