---
- name: Install app on OS
  ansible.builtin.include_tasks: "{{ playbook_dir }}/_shared_tasks/{{ 'mac_install_cask.yml' if ansible_system == 'Darwin' else 'win_install_package.yml' if ansible_system == 'Win32NT' else 'linux_install_package.yml' }}"
  vars:
    pkg_name: "{{ app_pkg_mac if ansible_system == 'Darwin' else app_pkg_win if ansible_system == 'Win32NT' else app_pkg_linux }}"
    app_name: "{{ app_name_mac | default('') }}"
  when: >
    (ansible_system == 'Darwin' and app_pkg_mac | default('') | length > 0) or
    (ansible_system == 'Win32NT' and app_pkg_win | default('') | length > 0) or
    (ansible_system == 'Linux' and app_pkg_linux | default('') | length > 0)
