---
- name: Check if dockutil is installed
  ansible.builtin.command: which dockutil
  register: dockutil_check
  changed_when: false
  failed_when: false

- name: Ensure dockutil is installed (macOS)
  ansible.builtin.command: brew install dockutil
  when: dockutil_check.rc != 0

- name: Remove default macOS Dock icons
  ansible.builtin.command: dockutil --remove '{{ item }}' --no-restart
  loop:
    - Launchpad
    - Safari
    - Messages
    - Mail
    - Maps
    - Photos
    - FaceTime
    - Calendar
    - Contacts
    - Reminders
    - Notes
    - Freeform
    - Music
    - TV
    - Podcasts
    - News
  register: dockutil_result
  failed_when: false
  changed_when: dockutil_result.rc == 0

- name: Restart macOS Dock to apply changes
  ansible.builtin.command: killall Dock
  changed_when: true