---
- name: Ensure dockutil is installed (macOS)
  community.general.homebrew:
    name: dockutil
    state: present

- name: Remove default macOS Dock icons
  ansible.builtin.command: dockutil --remove '{{ item }}' --no-restart
  loop:
    - Launchpad
    - Safari
    - Messages
    - Mail
    - Maps
    - Photos
    - FaceTime
    - Calendar
    - Contacts
    - Reminders
    - Notes
    - Freeform
    - Music
    - TV
    - Podcasts
    - News
  register: dockutil_result
  failed_when: false
  changed_when: "dockutil_result.rc == 0"
  notify: Restart Dock
