---
- name: Ensure this role runs only on macOS
  ansible.builtin.assert:
    that:
      - ansible_system == 'Darwin'

- name: Install mole on macOS
  community.general.homebrew:
    name: mole
    state: present
