---
- name: Ensure this role runs only on macOS
  ansible.builtin.assert:
    that:
      - ansible_system == 'Darwin'

- name: Run installer
  ansible.builtin.include_tasks: "{{ playbook_dir }}/_shared_tasks/installer/main.yml"
