---
- name: Ensure env directory exists
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/env"
    state: directory
    mode: "0755"
  when: ansible_system != 'Win32NT'

- name: Copy all environment files from config/user_env
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/config/user_env/"
    dest: "{{ ansible_user_dir }}/.config/env/"
    mode: "0755"
  when:
    - ansible_system != 'Win32NT'
    - (playbook_dir + '/config/user_env/') is directory

- name: Ensure env.sh is sourced in .zshrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    line: '[[ -f ~/.config/env/env.sh ]] && . ~/.config/env/env.sh'
    regexp: '\.config/env/env\.sh'
    state: present
    create: yes
  when: ansible_system != 'Win32NT'

- name: Ensure env.sh is sourced in .bashrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    line: '[[ -f ~/.config/env/env.sh ]] && . ~/.config/env/env.sh'
    regexp: '\.config/env/env\.sh'
    state: present
    create: yes
  when: ansible_system != 'Win32NT'
